### ISSUE TITLE
Error on import to the project

### ISSUE THREAD

**Issue by TheBricktop** [ababilinski/babilinapps.realsense.arbackground#1]
After adding the package to my project it throws some errors:

after updating to 2020: 

Assets\RealSenseSDK2.0\Scripts\RsARBackgroundRenderer.cs(14,13): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ababilinski** [comment]
@TheBricktop thank you for your bug report. I'll update the setup instructions. The script from the RealSense SDK has not been updated with a the correct `#define directives`. 

To bypass this try one of the following:
- remove the script throwing the error
- change the namespace reference to `UnityEngine.XR.ARBackgroundRenderer.Obsolete`

**Comment by TheBricktop** [comment]
I would  probably go with the second option but theres also a problem that when I type UnityEngine.XR.ARBackgroundRenderer.Obsolete then it throws an error that ARBackgroundrenderer is not a member of namespace.

**Comment by ababilinski** [comment]
@TheBricktop sorry, the full namespace is UnityEngine.XR.ARBackgroundRenderer.Obsolete the script is located here:
`babilinapps.realsense.arbackground/Runtime/Scripts/Obsolete/ARBackgroundRenderer.cs`
